# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: 25
  username: root
  password:
  timeout: 5000
  socket: /var/run/mysql-default/mysqld.sock
  port: 3306

development:
  <<: *default
  pool: 5
  host: <%= ENV['RAILS_DATABASE_HOST'] || '127.0.0.1' %>
  database: book_development

production:
  <<: *default
  database: book_production
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: <%= ENV['RAILS_DATABASE_HOST'] %>
  socket:
  port: <%= ENV['RAILS_DATABASE_PORT'] || 3306 %>
  pool: 40
